---
title: "filtered_non-filtered_full_data_plots"
output: html_document
date: "2023-10-11"
editor_options: 
  chunk_output_type: console
---

loading data
```{r}
udeg_rep1_b <- udeg_rep1
hdeg_rep1_b <- hdeg_rep1

hdeg_rep1_nano <- hdeg_rep1
udeg_rep1_nano <- udeg_rep1
```

Cumulative read length distribution plot

Selecting required columns- non filtered and filtered
```{r warning=FALSE, message=FALSE}
lh_b <- hdeg_rep1_b %>% 
  dplyr::select(Transcript, ReadLen)
lu_b <- udeg_rep1_b %>% 
  dplyr::select(Transcript, ReadLen)

lh_a <- hdeg_all_filtering %>% 
  dplyr::select(Transcript, new_ReadLen)
lu_a <- udeg_all_filtering %>% 
  dplyr::select(Transcript, new_ReadLen)

lh_bn <- hdeg_rep1_nano %>% 
  dplyr::select(Transcript, ReadLen)
lu_bn <- udeg_rep1_nano %>% 
  dplyr::select(Transcript, ReadLen)
```

Ordering the Read len columns
```{r warning=FALSE, message=FALSE}
lh2_b <- lh_b[order(lh_b$ReadLen), ]
lu2_b <- lu_b[order(lu_b$ReadLen), ]

lh2_a <- lh_a[order(lh_a$new_ReadLen), ]
lu2_a <- lu_a[order(lu_a$new_ReadLen), ]

lh2_bn <- lh_bn[order(lh_bn$ReadLen), ]
lu2_bn <- lu_bn[order(lu_bn$ReadLen), ]
```

Normalising between 0 and 1
```{r warning=FALSE, message=FALSE}
lh2_b$percent=(1:nrow(lh2_b))/nrow(lh2_b)
lu2_b$percent=(1:nrow(lu2_b))/nrow(lu2_b)

lh2_a$percent=(1:nrow(lh2_a))/nrow(lh2_a)
lu2_a$percent=(1:nrow(lu2_a))/nrow(lu2_a)

lh2_bn$percent=(1:nrow(lh2_bn))/nrow(lh2_bn)
lu2_bn$percent=(1:nrow(lu2_bn))/nrow(lu2_bn)
```

Plots
```{r warning=FALSE, message=FALSE}
ggplot()+
  geom_point(data = lh2_b, aes(x=percent, y=ReadLen), color="red")+
  geom_point(data = lu2_b, aes(x=percent, y=ReadLen), color="blue") + theme_bw() + ggtitle("Unfiltered- Read Length Distribution") + theme_bw() + labs(x="Percent", y="Read Length") + theme(axis.text=element_text(size=16), axis.title=element_text(size=18)) + theme(plot.title = element_text(size=18, face = "bold")) + ylim(0,15000)

ggplot()+
  geom_point(data = lh2_a, aes(x=percent, y=new_ReadLen), color="red")+
  geom_point(data = lu2_a, aes(x=percent, y=new_ReadLen), color="blue") + theme_bw() + ggtitle("Filtered- Read Length Distribution") + theme_bw() + labs(x="Percent", y="Read Length") + theme(axis.text=element_text(size=16), axis.title=element_text(size=18)) + theme(plot.title = element_text(size=18, face = "bold")) + ylim(0,15000)

ggplot()+
  geom_point(data = lh2_bn, aes(x=percent, y=ReadLen), color="red")+
  geom_point(data = lu2_bn, aes(x=percent, y=ReadLen), color="blue") + theme_bw() + ggtitle("Nanocount- Read Length Distribution") + theme_bw() + labs(x="Percent", y="Read Length") + theme(axis.text=element_text(size=16), axis.title=element_text(size=18)) + theme(plot.title = element_text(size=18, face = "bold")) + ylim(0,15000)
```

3' ends

Selecting required columns- non filtered and filtered
```{r warning=FALSE, message=FALSE}
lh_b <- hdeg_rep1_b %>% 
  dplyr::select(Transcript, end_without_sc)
lu_b <- udeg_rep1_b %>% 
  dplyr::select(Transcript, end_without_sc)

lh_a <- hdeg_all_filtering %>% 
  dplyr::select(Transcript, new_3_end)
lu_a <- udeg_all_filtering %>% 
  dplyr::select(Transcript, new_3_end)

lh_bn <- hdeg_rep1_nano %>% 
  dplyr::select(Transcript, end_without_sc)
lu_bn <- udeg_rep1_nano %>% 
  dplyr::select(Transcript, end_without_sc)
```

Ordering the 3' end columns
```{r warning=FALSE, message=FALSE}
lh2_b <- lh_b[order(lh_b$end_without_sc), ]
lu2_b <- lu_b[order(lu_b$end_without_sc), ]

lh2_a <- lh_a[order(lh_a$new_3_end), ]
lu2_a <- lu_a[order(lu_a$new_3_end), ]

lh2_bn <- lh_bn[order(lh_bn$end_without_sc), ]
lu2_bn <- lu_bn[order(lu_bn$end_without_sc), ]
```

Normalising between 0 and 1
```{r warning=FALSE, message=FALSE}
lh2_b$percent=(1:nrow(lh2_b))/nrow(lh2_b)
lu2_b$percent=(1:nrow(lu2_b))/nrow(lu2_b)

lh2_a$percent=(1:nrow(lh2_a))/nrow(lh2_a)
lu2_a$percent=(1:nrow(lu2_a))/nrow(lu2_a)

lh2_bn$percent=(1:nrow(lh2_bn))/nrow(lh2_bn)
lu2_bn$percent=(1:nrow(lu2_bn))/nrow(lu2_bn)
```

Plots
```{r warning=FALSE, message=FALSE}
ggplot()+
  geom_point(data = lh2_b, aes(x=percent, y=end_without_sc), color="red")+
  geom_point(data = lu2_b, aes(x=percent, y=end_without_sc), color="blue") + theme_bw() + ggtitle("Unfiltered- 3' end Distribution") + theme_bw() + labs(x="Percent", y="3' end") + theme(axis.text=element_text(size=16), axis.title=element_text(size=18)) + theme(plot.title = element_text(size=18, face = "bold")) + ylim(0,100000)

ggplot()+
  geom_point(data = lh2_a, aes(x=percent, y=new_3_end), color="red")+
  geom_point(data = lu2_a, aes(x=percent, y=new_3_end), color="blue") + theme_bw() + ggtitle("Filtered- 3' end Distribution") + theme_bw() + labs(x="Percent", y="3' end") + theme(axis.text=element_text(size=16), axis.title=element_text(size=18)) + theme(plot.title = element_text(size=18, face = "bold"))+ ylim(0,100000)

ggplot()+
  geom_point(data = lh2_bn, aes(x=percent, y=end_without_sc), color="red")+
  geom_point(data = lu2_bn, aes(x=percent, y=end_without_sc), color="blue") + theme_bw() + ggtitle("Nanocount- 3' end Distribution") + theme_bw() + labs(x="Percent", y="3' end") + theme(axis.text=element_text(size=16), axis.title=element_text(size=18)) + theme(plot.title = element_text(size=18, face = "bold")) + ylim(0,100000)
```

